workspace:
  base: /go
  path: src/github.com/bysir-zl/gokit_start

pipeline:
  build:
    image: golang:1.9
    commands:
      - go env
      - pwd
      - go version
      - go build

  publish:
      image: plugins/docker
      registry: https://index.docker.io/v1/ # 仓库
      repo: bysir/golang_base # docker仓库地址
      # mirror: https://docker.mirrors.ustc.edu.cn
      # 需要使用drone cli添加secrets: http://docs.drone.io/manage-secrets/
      secrets: [ docker_username, docker_password ]
      tags:
        - latest

  deploy:
      image: appleboy/drone-ssh
      host: 47.96.129.228
      username: root
      port: 22
      secrets: [ ssh_password ,password]
      script:
        - cd /root/app
        - docker-compose pull bysir/golang_base
        - docker-compose up
