workspace:
  base: /go
  path: src/github.com/bysir-zl/gokit_start

pipeline:
  build:
    image: golang:1.9
    commands:
      - go env
      - pwd
      - go version
      - go build

  publish:
      image: plugins/docker
      registry: hub.docker.com
      repo: bysir/golang_base
      mirror: https://docker.mirrors.ustc.edu.cn
      secrets: [ docker_username, docker_password ]
      tags:
        - latest
